name: validate-pull-request

on:
  - pull_request

jobs:
  format-source-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Get unformatted files
        id: changes
        run: |
          git fetch --depth=1 origin ${{ github.event.pull_request.base.ref }}
          git diff -z --name-only --diff-filter=ACMRT origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} | xargs -0 -I {} npx prettier --write "{}"
      - name: Commit formatted files
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add .
          if git diff --quiet; then
            echo "Nothing to format"
            exit 0
          fi
          git commit -m "chore: format source code with Prettier"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
